---
resources:
- name: selfhydro
  type: git
  source:
    uri: https://github.com/selfhydro/selfhydro.git

- name: selfhydro-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/selfhydro

- name: version
  type: semver
  source:
    driver: gcs

- name: selfhydro-release
  type: github-release
  source:
    owner: selfhydro
    repository: selfhydro
    access_token: ((github-access-token))

jobs:
- name: tests
  plan:
  - get: selfhydro
    trigger: true
  - task: unit-test
    file: selfhydro/.ci/unit-test.yml

- name: build
  plan:
  - get: version
    params: {bump: patch}
  - get: selfhydro
    trigger: true
    passed: [tests]
  - put: version
    params: {file: version/version}
  - task: build-linux-arm
    file: selfhydro/.ci/build-linux-arm.yml
  - put: selfhydro-release
    params:
      name: release/name
      tag: release/tag
      body: release/body
      globs:
       [release/selfhydro, release/docker-args]

- name: create-docker-image
  plan:
  - get: selfhydro-release
    trigger: true
    passed: [build]
  - get: selfhydro
    trigger: true
    passed: [build]
  - put: selfhydro-docker-image
    params:
      build: selfhydro/.ci/docker
      build_args_file: selfhydro-release/docker-args
      tag: selfhydro-release/tag

- name: deploy
  plan:
  - get: selfhydro-release
    trigger: true
    passed: [build]
  - get: selfhydro
    trigger: true
    passed: [build]
  - task: deploy
    file: selfhydro/.ci/deploy.yml
    params:
         DOCKER_USERNAME: ((docker-hub-username))
         DOCKER_PASSWORD: ((docker-hub-password))
