---
resources:
- name: selfhydro
  type: git
  source:
    uri: https://github.com/bchalk101/selfhydro.git

jobs:
- name: tests
  plan:
  - get: selfhydro
    trigger: true
  - task: unit-test
    file: selfhydro/.ci/unit-test.yml

- name: deploy-selfhydro
  plan:
  - get: selfhydro
    trigger: true
    passed: [tests]
  - task: build-linux-arm
    file: selfhydro/.ci/build-linux-arm.yml
  - put: project-bin
    params:
      file: binary/selfhydro
  - task: deploy
    file: selfhydro/.ci/deploy.yml
    params:
      DEPLOY_KEY: ((selfhydro-rpi.private_key))
