---
resources:
- name: selfhydro
  type: git
  source:
    uri: https://github.com/bchalk101/selfhydro.git

- name: selfhydro-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/selfhydro-release

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:bchalk101/selfhydro-version.git
    branch: master
    file: version
    private_key: ((selfhydro-version-repo.private_key))

- name: selfhydro-release
  type: github-release
  source:
    owner: bchalk101
    repository: selfhydro
    access_token: ((github-access-token))

jobs:    
- name: tests
  plan:
  - get: selfhydro
    trigger: true
  - task: unit-test
    file: selfhydro/.ci/unit-test.yml

- name: build
  plan:
  - get: version
    params: {bump: patch}
  - get: selfhydro
    trigger: true
    passed: [tests]
  - put: version
    params: {file: version/version}
  - task: build-linux-arm
    file: selfhydro/.ci/build-linux-arm.yml
  - put: selfhydro-release
    params:
      name: release/name
      tag: release/tag
      body: release/body
      globs:
      - release/selfhydro

- name: publish
  plan:
  - get: selfhydro-release
    trigger: true
    passed: [build]
  - get: selfhydro
    trigger: true
    passed: [build]
  - task: publish-docker-image
    privileged: true
    file: selfhydro/.ci/publish-docker-image.yml
    params:
          DOCKER_USERNAME: ((docker-hub-username))
          DOCKER_PASSWORD: ((docker-hub-password))
#  - put: selfhydro-docker-image
#    params:
#      build: selfhydro/.ci/docker
#      build_args:
#       TAG: selfhydro-release/tag

- name: deploy
  plan:
  - get: selfhydro-release
    trigger: true
    passed: [publish]
  - get: selfhydro-docker-image
    trigger: true
  - task: deploy
    file: selfhydro/.ci/deploy.yml
    params:
          DEPLOY_KEY: ((selfhydro-rpi-deploy-key.private_key))
          DOCKER_USERNAME: ((docker-hub-username))
          DOCKER_PASSWORD: ((docker-hub-password))
