[package]
name = "sensors"
version = "0.1.0"
edition = "2021"

[dependencies]
rppal = "0.22.1"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] } 